---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "lts"
inputs:
  - name: src-repo
outputs:
  - name: node_modules
run:
  path: sh
  args:
    - -exc
    - |
      cd src-repo
      NODE_ENV=dev
      npx audit-ci -l
      echo "npm audit completed"
      npm ci
      mv node_modules ../node_modules/node_modules
      pwd
      ls -rlt
      echo "starting npm test"
